package it.lorenz

// format: off
object StatoRPTEnum extends Enumeration {
  val READY, RPT_RISOLTA_OK, RPT_RISOLTA_KO, RPT_RICEVUTA_NODO, RPT_ACCETTATA_NODO, RPT_RIFIUTATA_NODO, RPT_ERRORE_INVIO_A_PSP,
  RPT_INVIATA_A_PSP, RPT_ACCETTATA_PSP, RPT_RIFIUTATA_PSP, RPT_ANNULLATA_WISP, RT_GENERATA_NODO,
  RT_RICEVUTA_NODO, RT_RIFIUTATA_NODO, RT_ACCETTATA_NODO, RT_ACCETTATA_PA, RT_RIFIUTATA_PA,
  RT_ESITO_SCONOSCIUTO_PA, RT_INVIATA_PA, VERIFIED, RECEIVED, RPT_DECORSI_TERMINI,
  RPT_ESITO_SCONOSCIUTO_PSP, RPT_PARCHEGGIATA_NODO, RPT_PARCHEGGIATA_NODO_MOD3, RT_ERRORE_INVIO_A_PA, RR_RICEVUTA_NODO,
  RR_RIFIUTATA_NODO, RR_ACCETTATA_NODO, RR_INVIATA, RR_ESITO_SCONOSCIUTO, RR_ACCETTATA,
  RR_RIFIUTATA, ER_RICEVUTA_NODO, ER_RIFIUTATA_NODO, ER_ACCETTATA_NODO, ER_INVIATA,
  ER_ESITO_SCONOSCIUTO, ER_ACCETTATA, ER_RIFIUTATA, RT_REVOCATA, RPT_ANNULLATA_NODO = Value
}
